# coding: utf-8
# Copyright 2018 Vauxoo
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
from odoo import models, fields


class MrpProduction(models.Model):
    _inherit = "mrp.production"

    account_analytic_in_id = fields.Many2one(
        'account.analytic.account',
        'R.M. Analytic Account', readonly=True,
        copy=False,
        states={'confirmed': [('readonly', False)]},
        help='Analytic account that will be set on journal items '
        'generated by raw materials stock moves')

    account_analytic_out_id = fields.Many2one(
        'account.analytic.account',
        'F.P. Analytic Account', readonly=True,
        copy=False,
        states={'confirmed': [('readonly', False)]},
        help='Analytic account that will be set on journal items '
        'generated by finished product stock moves')

    analytic_tag_ids = fields.Many2many(
        'account.analytic.tag', string='Analytic Tags',
        copy=False,
        states={'confirmed': [('readonly', False)]})
