# coding: utf-8
# Copyright 2018 Vauxoo
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
from odoo import models


class StockMove(models.Model):
    _inherit = "stock.move"

    def _prepare_account_move_line(
            self, qty, cost, credit_account_id, debit_account_id):
        """Setting analytic account to the new accoun move line generated by a
        stock move"""
        res = super(StockMove, self)._prepare_account_move_line(
            qty, cost, credit_account_id, debit_account_id)
        for lines in res:
            aml = lines[2]
            aml_type = (
                aml.get('account_id') == debit_account_id and 'credit' or
                aml.get('account_id') == credit_account_id and 'debit' or
                'None')
            set_account = {
                'credit': lambda a: {
                    'analytic_account_id':
                    a.raw_material_production_id.account_analytic_in_id.id,
                    'analytic_tag_ids':
                    [(6, 0,
                      a.raw_material_production_id.analytic_tag_ids.ids)]}
                if a.raw_material_production_id else {},
                'debit': lambda a: {
                    'analytic_account_id':
                    a.production_id.account_analytic_out_id.id,
                    'analytic_tag_ids': [
                        (6, 0, a.production_id.analytic_tag_ids.ids)]}
                if a.production_id else {}
            }
            aml.update(set_account.get(aml_type, lambda a: {})(self))
        return res
